services:
  fastapi:
    build: ./backend
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - app-network
    restart: unless-stopped

  nextjs:
    build: ./frontend
    container_name: nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://fastapi:8000
      - NODE_ENV=development
    depends_on:
      - fastapi
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
